"""create initial user service tables

Revision ID: 4f6c51ab2391
Revises: 
Create Date: 2026-10-09 09:57:21.346707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6c51ab2391'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BINARY(length=16), nullable=False, comment='Identificador UUID do usuário associado ao token.'),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment='Nome completo informado pelo usuário.'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Endereço de e-mail do usuário.'),
    sa.Column('whatsapp', sa.String(length=30), nullable=False, comment='Número de WhatsApp utilizado para contato.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash criptográfico da senha do usuário.'),
    sa.Column('confirmed', sa.Boolean(), nullable=False, comment='Indica se o usuário confirmou o endereço de e-mail.'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Indica se o usuário possui privilégios administrativos.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora da criação do usuário em UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora da última atualização do usuário em UTC.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_confirmation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único do registro do token.'),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False, comment='Identificador UUID do usuário associado ao token.'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='Hash SHA-256 do token de confirmação.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de criação do token em UTC.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de expiração do token em UTC.'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Data e hora em que o token foi revogado em UTC.'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Data e hora em que o token foi utilizado.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_confirmation_tokens_user_id'), 'email_confirmation_tokens', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_created_at'), 'password_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único do token de redefinição de senha.'),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False, comment='Identificador UUID do usuário associado ao token.'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Hash do token de redefinição de senha.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de criação do token em UTC.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de expiração do token em UTC.'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Data e hora em que o token foi utilizado em UTC.'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Data e hora em que o token foi revogado em UTC.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identificador interno do refresh token.'),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False, comment='Identificador UUID do usuário associado ao refresh token.'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='Hash SHA-256 do refresh token.'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do refresh token.'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Data e hora de expiração do refresh token.'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='Data e hora de revogação do refresh token.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.BINARY(length=16), nullable=False, comment='Identificador único do endereço.'),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False, comment='Identificador do usuário proprietário do endereço.'),
    sa.Column('label', sa.String(length=50), nullable=True, comment='Nome utilizado pelo usuário para identificar o endereço.'),
    sa.Column('zip_code', sa.String(length=9), nullable=False, comment='CEP do endereço.'),
    sa.Column('street', sa.String(length=255), nullable=False, comment='Logradouro do endereço.'),
    sa.Column('number', sa.String(length=20), nullable=False, comment='Número do endereço.'),
    sa.Column('complement', sa.String(length=100), nullable=True, comment='Complemento do endereço.'),
    sa.Column('neighborhood', sa.String(length=100), nullable=False, comment='Bairro do endereço.'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='Cidade do endereço.'),
    sa.Column('state', sa.String(length=2), nullable=False, comment='Sigla do estado do endereço.'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Indica se este é o endereço padrão do usuário.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora de criação do endereço em UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora da última atualização do endereço em UTC.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_created_at'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_email_confirmation_tokens_user_id'), table_name='email_confirmation_tokens')
    op.drop_table('email_confirmation_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
